version: "3.9"  # optional since v1.27.0
services: 
  api:
    build:
        dockerfile: Dockerfile.API
    ports:
      - "6000:80"
    depends_on:
      - db
  db:
    image: bakery-api 
    ports:
      - "1433:1433"
